# Generated by Django 3.2.4 on 2021-07-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_text',
            new_name='posts_text',
        ),
    ]
